---
apiVersion: v1
kind: Service
metadata:
  name: evilservice
spec:
  type: ClusterIP
  ports:
  - port: 2223
    targetPort: ssh
    protocol: TCP
    name: ssh
  selector:
    app: evilpod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evilaccount